{
 "title": "example",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) AS \"Status\"\nFROM now\nWHERE NOW = 1;",
     "rawQueryText": "SELECT COUNT(*) AS \"Status\"\nFROM now\nWHERE NOW = 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) AS \"Status\"\nFROM now\nWHERE NOW = 0;",
     "rawQueryText": "SELECT COUNT(*) AS \"Status\"\nFROM now\nWHERE NOW = 0;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TOTAL SCANNED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) AS \"Total scanned\"\nFROM now;",
     "rawQueryText": "SELECT COUNT(*) AS \"Total scanned\"\nFROM now;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DEVICE LIST",
   "type": "table",
   "gridPos": { "h": 16, "w": 20, "x": 1, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT\n  NAME AS \"Device Name\",\n  DNS AS \"DNS\",\n  IFACE AS \"Interface\",\n  IP AS \"IP Address\",\n  MAC AS \"MAC Address\",\n  HW AS \"Hardware\",\n  DATE AS \"Last Seen\",\n  NOW AS \"Status\"\nFROM now;",
     "rawQueryText": "SELECT\n  NAME AS \"Device Name\",\n  DNS AS \"DNS\",\n  IFACE AS \"Interface\",\n  IP AS \"IP Address\",\n  MAC AS \"MAC Address\",\n  HW AS \"Hardware\",\n  DATE AS \"Last Seen\",\n  NOW AS \"Status\"\nFROM now;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}